// <auto-generated />
using System;
using BoletoCinema.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoletoCinema.Migrations
{
    [DbContext(typeof(BoletoContext))]
    [Migration("20210104041617_Movie_addColumn_poster")]
    partial class Movie_addColumn_poster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Actor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("actors");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Branch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.ContactForm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("contactForms");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Discount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("discount_percent")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("discounts");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("published_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("summery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trailer_path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Actor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("actor_id")
                        .HasColumnType("int");

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("actor_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_Actors");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_Categories");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Discount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("discount_id")
                        .HasColumnType("int");

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("discount_id");

                    b.HasIndex("movie_id");

                    b.ToTable("Movie_Discount");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("total_price")
                        .HasColumnType("float");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("review_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("review_id");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("heart_rate")
                        .HasColumnType("int");

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("movie_id");

                    b.HasIndex("user_id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("branch_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("branch_id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.Property<int>("room_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("movie_id");

                    b.HasIndex("room_id");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Seat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("room_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("room_id");

                    b.ToTable("seats");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Seat_Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("seat_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("ticket_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("seat_id");

                    b.HasIndex("ticket_id");

                    b.ToTable("seat_status");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Ticket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Roomid")
                        .HasColumnType("int");

                    b.Property<int?>("order_id")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int?>("schedule_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Roomid");

                    b.HasIndex("order_id");

                    b.HasIndex("schedule_id");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("displayname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("rule")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.UserDiscount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("discount_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("discount_id");

                    b.HasIndex("user_id");

                    b.ToTable("userDiscounts");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.ContactForm", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.User", "user")
                        .WithMany("contactForms")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Actor", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Actor", "actor")
                        .WithMany("movie_Actors")
                        .HasForeignKey("actor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Movie", "movie")
                        .WithMany("movie_Actors")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actor");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Category", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Category", "category")
                        .WithMany("movie_category")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Movie", "movie")
                        .WithMany("movie_Categories")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie_Discount", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Discount", "discount")
                        .WithMany("movieDiscounts")
                        .HasForeignKey("discount_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Movie", "movie")
                        .WithMany("movieDiscounts")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("discount");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Order", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Report", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Review", "review")
                        .WithMany("report")
                        .HasForeignKey("review_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("review");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Review", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Movie", "movie")
                        .WithMany("reviews")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Room", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Branch", "branch")
                        .WithMany("rooms")
                        .HasForeignKey("branch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Schedule", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Movie", "movie")
                        .WithMany("schedules")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Room", "room")
                        .WithMany("schedules")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("room");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Seat", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Room", "room")
                        .WithMany("seats")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("room");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Seat_Status", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Seat", "Seat")
                        .WithMany("seat_Statuses")
                        .HasForeignKey("seat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Ticket", "Ticket")
                        .WithMany("seat_Statuses")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Ticket", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Room", null)
                        .WithMany("tickets")
                        .HasForeignKey("Roomid");

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Order", "order")
                        .WithMany("tickets")
                        .HasForeignKey("order_id");

                    b.HasOne("BoletoCinema.Areas.Admin.Models.Schedule", "schedule")
                        .WithMany("tickets")
                        .HasForeignKey("schedule_id");

                    b.Navigation("order");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.UserDiscount", b =>
                {
                    b.HasOne("BoletoCinema.Areas.Admin.Models.Discount", "discount")
                        .WithMany("user_discount")
                        .HasForeignKey("discount_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoletoCinema.Areas.Admin.Models.User", "user")
                        .WithMany("userDiscounts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("discount");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Actor", b =>
                {
                    b.Navigation("movie_Actors");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Branch", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Category", b =>
                {
                    b.Navigation("movie_category");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Discount", b =>
                {
                    b.Navigation("movieDiscounts");

                    b.Navigation("user_discount");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Movie", b =>
                {
                    b.Navigation("movie_Actors");

                    b.Navigation("movie_Categories");

                    b.Navigation("movieDiscounts");

                    b.Navigation("reviews");

                    b.Navigation("schedules");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Order", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Review", b =>
                {
                    b.Navigation("report");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Room", b =>
                {
                    b.Navigation("schedules");

                    b.Navigation("seats");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Schedule", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Seat", b =>
                {
                    b.Navigation("seat_Statuses");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.Ticket", b =>
                {
                    b.Navigation("seat_Statuses");
                });

            modelBuilder.Entity("BoletoCinema.Areas.Admin.Models.User", b =>
                {
                    b.Navigation("contactForms");

                    b.Navigation("orders");

                    b.Navigation("reviews");

                    b.Navigation("userDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
